import {  Dimensions } from 'react-native';

export default {
  screenHeight : Math.round(Dimensions.get('window').height),
  screenWidth : Math.round(Dimensions.get('window').width),
  imagesIce : [
    require("../assets/images/ice/1.png"),
    require("../assets/images/ice/2.png"),
    require("../assets/images/ice/3.png"),
    require("../assets/images/ice/4.png"),
    require("../assets/images/ice/5.png"),
    require("../assets/images/ice/6.png"),
    require("../assets/images/ice/7.png"),
    require("../assets/images/ice/8.png"),
    require("../assets/images/ice/9.png"),
    require("../assets/images/ice/10.png"),
    require("../assets/images/ice/11.png"),
    require("../assets/images/ice/12.png"),
    require("../assets/images/ice/13.png"),
    require("../assets/images/ice/14.png"),
    require("../assets/images/ice/15.png"),
    require("../assets/images/ice/16.png"),
    require("../assets/images/ice/17.png"),
    require("../assets/images/ice/18.png"),
    require("../assets/images/ice/19.png"),
    require("../assets/images/ice/20.png"),
    require("../assets/images/ice/21.png"),
    require("../assets/images/ice/22.png"),
    require("../assets/images/ice/23.png"),
    require("../assets/images/ice/24.png"),
    require("../assets/images/ice/25.png"),
  ],

  imagesSeal : [
    require("../assets/images/seal/1.png"),
    require("../assets/images/seal/2.png"),
    require("../assets/images/seal/3.png"),
    require("../assets/images/seal/4.png"),
    require("../assets/images/seal/5.png"),
  ],

  imagesBear : [
    require("../assets/images/bear/1.png"),
    require("../assets/images/bear/2.png"),
    require("../assets/images/bear/3.png"),
    require("../assets/images/bear/4.png"),
    require("../assets/images/bear/5.png"),
  ],

  textSeal : [
    "Guy, you sucks ...",
    "I never seen someone as bad.",
    "I cannot count on you",
    "Just stop this game, it's too difficult for you",
    "Don't try again, let me die !",
    "You really are a disaster",
    "My grand mother seal is better than you",
    "Please do better, you are so bad",
    "Are you blind ? It was so easy",
    "Crap, you play like a shit",
    "Forget this game, not for you",
    "You will never win this game, sorry"

  ],

  textBear : [
    "Fucking looser",
    "You are the worst player I ever seen",
    "Polar bear will die because of you",
    "I'm not joking, stop to ridicule yoursekf",
    "finally, you'r not so bad, in an other life",
    "Antartic will totally melt before you win this game",
    "If I catch you again to play as badly, I will kill you",
    "Hopefully, you can't be ugly as the score you did",
    "My brother is 2 year old, but better than you",
    "One polar bear less, since I will kill myself to not see you play again",
    "Fortunately, I will never cross you in real life",
    "Water wets, fire burn, and you loose"

  ],

  images1 : [
    require("../assets/images/1/1.png"),
    require("../assets/images/1/2.png"),
    require("../assets/images/1/3.png"),
    require("../assets/images/1/4.png"),
    require("../assets/images/1/5.png"),
    require("../assets/images/1/6.png"),
    require("../assets/images/1/7.png"),
    require("../assets/images/1/8.png"),
    require("../assets/images/1/9.png"),
    require("../assets/images/1/10.png"),
    require("../assets/images/1/11.png"),
    require("../assets/images/1/12.png"),
    require("../assets/images/1/13.png"),
    require("../assets/images/1/14.png"),
    require("../assets/images/1/15.png"),
    require("../assets/images/1/16.png"),
    require("../assets/images/1/17.png"),
    require("../assets/images/1/18.png"),
    require("../assets/images/1/19.png"),
    require("../assets/images/1/20.png"),
    require("../assets/images/1/21.png"),
    require("../assets/images/1/22.png"),
    require("../assets/images/1/23.png"),
    require("../assets/images/1/24.png"),
    require("../assets/images/1/25.png"),
  ],

  images2 : [
    require("../assets/images/2/1.png"),
    require("../assets/images/2/2.png"),
    require("../assets/images/2/3.png"),
    require("../assets/images/2/4.png"),
    require("../assets/images/2/5.png"),
    require("../assets/images/2/6.png"),
    require("../assets/images/2/7.png"),
    require("../assets/images/2/8.png"),
    require("../assets/images/2/9.png"),
    require("../assets/images/2/10.png"),
    require("../assets/images/2/11.png"),
    require("../assets/images/2/12.png"),
    require("../assets/images/2/13.png"),
    require("../assets/images/2/14.png"),
    require("../assets/images/2/15.png"),
    require("../assets/images/2/16.png"),
    require("../assets/images/2/17.png"),
    require("../assets/images/2/18.png"),
    require("../assets/images/2/19.png"),
    require("../assets/images/2/20.png"),
    require("../assets/images/2/21.png"),
    require("../assets/images/2/22.png"),
    require("../assets/images/2/23.png"),
    require("../assets/images/2/24.png"),
    require("../assets/images/2/25.png"),
  ],

  images3 : [
    require("../assets/images/3/1.png"),
    require("../assets/images/3/2.png"),
    require("../assets/images/3/3.png"),
    require("../assets/images/3/4.png"),
    require("../assets/images/3/5.png"),
    require("../assets/images/3/6.png"),
    require("../assets/images/3/7.png"),
    require("../assets/images/3/8.png"),
    require("../assets/images/3/9.png"),
    require("../assets/images/3/10.png"),
    require("../assets/images/3/11.png"),
    require("../assets/images/3/12.png"),
    require("../assets/images/3/13.png"),
    require("../assets/images/3/14.png"),
    require("../assets/images/3/15.png"),
    require("../assets/images/3/16.png"),
    require("../assets/images/3/17.png"),
    require("../assets/images/3/18.png"),
    require("../assets/images/3/19.png"),
    require("../assets/images/3/20.png"),
    require("../assets/images/3/21.png"),
    require("../assets/images/3/22.png"),
    require("../assets/images/3/23.png"),
    require("../assets/images/3/24.png"),
    require("../assets/images/3/25.png"),
  ],

  images4 : [
    require("../assets/images/4/1.png"),
    require("../assets/images/4/2.png"),
    require("../assets/images/4/3.png"),
    require("../assets/images/4/4.png"),
    require("../assets/images/4/5.png"),
    require("../assets/images/4/6.png"),
    require("../assets/images/4/7.png"),
    require("../assets/images/4/8.png"),
    require("../assets/images/4/9.png"),
    require("../assets/images/4/10.png"),
    require("../assets/images/4/11.png"),
    require("../assets/images/4/12.png"),
    require("../assets/images/4/13.png"),
    require("../assets/images/4/14.png"),
    require("../assets/images/4/15.png"),
    require("../assets/images/4/16.png"),
    require("../assets/images/4/17.png"),
    require("../assets/images/4/18.png"),
    require("../assets/images/4/19.png"),
    require("../assets/images/4/20.png"),
    require("../assets/images/4/21.png"),
    require("../assets/images/4/22.png"),
    require("../assets/images/4/23.png"),
    require("../assets/images/4/24.png"),
    require("../assets/images/4/25.png"),
  ]
}
